<?php
require_once __DIR__ . '/config/bootstrap.php';
$pageTitle='Tambah Produk'; $active='create';
$categories=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();
$suppliers=$pdo->query('SELECT * FROM suppliers ORDER BY name')->fetchAll(); $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf(); $name=trim($_POST['name']??''); $category=(int)($_POST['category_id']??0); $supplier=(int)($_POST['supplier_id']??0); $price=(float)($_POST['price']??0); $stock=(int)($_POST['stock']??0);
 if($name==='')$errors[]='Nama produk wajib diisi.'; if(!$category)$errors[]='Kategori wajib dipilih.'; if(!$supplier)$errors[]='Supplier wajib dipilih.'; if($price<0)$errors[]='Harga tidak boleh negatif.'; if($stock<0)$errors[]='Stok tidak boleh negatif.';
 if(!$errors){$stmt=$pdo->prepare('INSERT INTO products(name,category_id,supplier_id,price,stock) VALUES(?,?,?,?,?)');$stmt->execute([$name,$category,$supplier,$price,$stock]);$log=$pdo->prepare('INSERT INTO activity_logs(action,description) VALUES(?,?)');$log->execute(['CREATE','Menambahkan produk: '.$name]);flash('success','Produk berhasil ditambahkan.');redirect('index.php?page=products');}
}
require __DIR__.'/partials/header.php';
?><section class="card form-card"><div class="card-head"><div><h2>Form Produk Baru</h2><span class="muted">Lengkapi data lalu simpan.</span></div></div><?php if($errors): ?><div class="flash error">⚠ <?= e(implode(' ',$errors)) ?></div><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><div class="form-grid"><div class="field full"><label>Nama Produk</label><input class="input" name="name" value="<?= e($_POST['name']??'') ?>" required placeholder="Contoh: Mouse Wireless"></div><div class="field"><label>Kategori</label><select class="select" name="category_id" required><option value="">Pilih kategori</option><?php foreach($categories as $c): ?><option value="<?= $c['id'] ?>" <?= ((int)($_POST['category_id']??0)===$c['id'])?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Supplier</label><select class="select" name="supplier_id" required><option value="">Pilih supplier</option><?php foreach($suppliers as $s): ?><option value="<?= $s['id'] ?>" <?= ((int)($_POST['supplier_id']??0)===$s['id'])?'selected':'' ?>><?= e($s['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Harga</label><input class="input" type="number" name="price" min="0" step="0.01" value="<?= e($_POST['price']??'') ?>" required></div><div class="field"><label>Stok</label><input class="input" type="number" name="stock" min="0" value="<?= e($_POST['stock']??'') ?>" required></div></div><div class="form-actions"><a class="btn btn-light" href="index.php?page=products">Batal</a><button class="btn btn-primary" type="submit">Simpan Produk</button></div></form></section><?php require __DIR__.'/partials/footer.php'; ?>
