<?php
require_once __DIR__ . '/config/bootstrap.php';
$id=(int)($_GET['id']??0); $stmt=$pdo->prepare('SELECT * FROM products WHERE id=?'); $stmt->execute([$id]); $product=$stmt->fetch();
if(!$product){flash('error','Produk tidak ditemukan.');redirect('index.php?page=products');}
$categories=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll(); $suppliers=$pdo->query('SELECT * FROM suppliers ORDER BY name')->fetchAll(); $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf(); $name=trim($_POST['name']??''); $category=(int)($_POST['category_id']??0); $supplier=(int)($_POST['supplier_id']??0); $price=(float)($_POST['price']??0); $stock=(int)($_POST['stock']??0);
 if($name==='')$errors[]='Nama produk wajib diisi.'; if(!$category)$errors[]='Kategori wajib dipilih.'; if(!$supplier)$errors[]='Supplier wajib dipilih.'; if($price<0)$errors[]='Harga tidak boleh negatif.'; if($stock<0)$errors[]='Stok tidak boleh negatif.';
 if(!$errors){$up=$pdo->prepare('UPDATE products SET name=?,category_id=?,supplier_id=?,price=?,stock=? WHERE id=?');$up->execute([$name,$category,$supplier,$price,$stock,$id]);$log=$pdo->prepare('INSERT INTO activity_logs(action,description) VALUES(?,?)');$log->execute(['UPDATE','Mengubah produk: '.$name]);flash('success','Produk berhasil diperbarui.');redirect('index.php?page=products');}
 $product=array_merge($product,['name'=>$name,'category_id'=>$category,'supplier_id'=>$supplier,'price'=>$price,'stock'=>$stock]);
}
$pageTitle='Edit Produk';$active='products';require __DIR__.'/partials/header.php';
?><section class="card form-card"><div class="card-head"><div><h2>Edit Produk #<?= $id ?></h2><span class="muted">Perbarui data produk dan simpan perubahan.</span></div></div><?php if($errors): ?><div class="flash error">⚠ <?= e(implode(' ',$errors)) ?></div><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><div class="form-grid"><div class="field full"><label>Nama Produk</label><input class="input" name="name" value="<?= e($product['name']) ?>" required></div><div class="field"><label>Kategori</label><select class="select" name="category_id" required><?php foreach($categories as $c): ?><option value="<?= $c['id'] ?>" <?= $product['category_id']==$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Supplier</label><select class="select" name="supplier_id" required><?php foreach($suppliers as $s): ?><option value="<?= $s['id'] ?>" <?= $product['supplier_id']==$s['id']?'selected':'' ?>><?= e($s['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Harga</label><input class="input" type="number" name="price" min="0" step="0.01" value="<?= e((string)$product['price']) ?>" required></div><div class="field"><label>Stok</label><input class="input" type="number" name="stock" min="0" value="<?= e((string)$product['stock']) ?>" required></div></div><div class="form-actions"><a class="btn btn-light" href="index.php?page=products">Batal</a><button class="btn btn-primary" type="submit">Simpan Perubahan</button></div></form></section><?php require __DIR__.'/partials/footer.php'; ?>
